INSERT INTO MEMBER(SEQ, NAME, AGE, ADDRESS) VALUES(1L, '홍길동', 20, '서울시 강남구');
INSERT INTO MEMBER(SEQ, NAME, AGE, ADDRESS) VALUES(2L, '아이유', 25, '서울시 청담동');
INSERT INTO MEMBER(SEQ, NAME, AGE, ADDRESS) VALUES(3L, '김연아', 19, '경기도 성남시 수지구');
INSERT INTO MEMBER(SEQ, NAME, AGE, ADDRESS) VALUES(4L, '손예진', 35, '포항시 남구');
INSERT INTO MEMBER(SEQ, NAME, AGE, ADDRESS) VALUES(5L, '원빈', 41, '대전시 서구');